### ISSUE TITLE
valgrind error (and segfault) when uploading to S3 with TransferClient

### ISSUE THREAD

**Issue by carlos-markavip** [awslabs/aws-sdk-cpp#101]
CentOS Linux release 7.2.1511 (Core),  on EC2
commit 01a57f0b343d78c286f29168ca27671b7b9d18e0
debug build without custom memory management

With https://gist.github.com/carlos-markavip/83c51847c8ad7995f0cb I'm getting a segfault intermittently and the following error under valgrind:

==12058== Memcheck, a memory error detector
==12058== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==12058== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==12058== Command: ./upload
==12058== 
uploading 0.bin...
==12058== Thread 2:
==12058== Invalid read of size 8
==12058==    at 0x4EAE407: Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E91499: Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E917DA: Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E937B0: Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x549FDD1: Aws::S3::S3Client::PutObject(Aws::S3::Model::PutObjectRequest const&) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-s3.so)
==12058==    by 0x549BAF9: Aws::S3::S3Client::PutObjectAsyncHelper(Aws::S3::Model::PutObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::PutObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-s3.so)
==12058==    by 0x586221F: ??? (in /usr/lib64/libstdc++.so.6.0.19)
==12058==    by 0x6395DC4: start_thread (in /usr/lib64/libpthread-2.17.so)
==12058==    by 0x60C321C: clone (in /usr/lib64/libc-2.17.so)
==12058==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==12058== 
==12058== 
==12058== Process terminating with default action of signal 11 (SIGSEGV)
==12058==  Access not within mapped region at address 0x0
==12058==    at 0x4EAE407: Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E91499: Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E917DA: Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x4E937B0: Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-core.so)
==12058==    by 0x549FDD1: Aws::S3::S3Client::PutObject(Aws::S3::Model::PutObjectRequest const&) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-s3.so)
==12058==    by 0x549BAF9: Aws::S3::S3Client::PutObjectAsyncHelper(Aws::S3::Model::PutObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::PutObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (in /opt/procactive/lib/linux/intel64/Release/libaws-cpp-sdk-s3.so)
==12058==    by 0x586221F: ??? (in /usr/lib64/libstdc++.so.6.0.19)
==12058==    by 0x6395DC4: start_thread (in /usr/lib64/libpthread-2.17.so)
==12058==    by 0x60C321C: clone (in /usr/lib64/libc-2.17.so)
==12058==  If you believe this happened as a result of a stack
==12058==  overflow in your program's main thread (unlikely but
==12058==  possible), you can try to increase the size of the
==12058==  main thread stack using the --main-stacksize= flag.
==12058==  The main thread stack size used in this run was 8388608.
==12058== 
==12058== HEAP SUMMARY:
==12058==     in use at exit: 8,895,976 bytes in 6,704 blocks
==12058==   total heap usage: 10,744 allocs, 4,040 frees, 12,814,806 bytes allocated
==12058== 
==12058== LEAK SUMMARY:
==12058==    definitely lost: 0 bytes in 0 blocks
==12058==    indirectly lost: 0 bytes in 0 blocks
==12058==      possibly lost: 3,209,711 bytes in 3,924 blocks
==12058==    still reachable: 5,686,265 bytes in 2,780 blocks
==12058==         suppressed: 0 bytes in 0 blocks
==12058== Rerun with --leak-check=full to see details of leaked memory
==12058== 
==12058== For counts of detected and suppressed errors, rerun with: -v
==12058== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)

**Comment by JonathanHenson** [comment]
We had a bug a while back with our curl implementation. Could you provide the revision of the SDK you are using and also your curl version?

**Comment by carlos-markavip** [comment]
I'm using the SDK code at commit 01a57f0
libcurl.x86_64 7.29.0-25.el7.centos

**Comment by JonathanHenson** [comment]
dang, well that's not it. Could you upload your log. That will let me see exactly where in that method it is failing.

**Comment by carlos-markavip** [comment]
here's the log, with Trace log level

[aws_sdk_2016-02-14-09.log.txt](https://github.com/awslabs/aws-sdk-cpp/files/129604/aws_sdk_2016-02-14-09.log.txt)

**Comment by JonathanHenson** [comment]
I don't immediately see anything here. Could you uncomment line 209 so we can see where we are in curl when the error happens? Also, could you add some tracer log statements after line 155 so we can see exactly where we are segfault out? Then maybe we can drill down on the logs and the curl output.

I wish I could immediately see the problem, but I haven't been able to reproduce the issue with the same exact code on my side.

**Comment by JonathanHenson** [comment]
Also, as an experiment, could you try using S3 PutObject directly?

**Comment by JonathanHenson** [comment]
We just found an issue that causes intermittent segfaults in libcurl and pushed out a fix. Can you pull down and see if your issue is resolved?

**Comment by carlos-markavip** [comment]
Pulled (3fe46f05d1c58fc946045d3b860a79c88d76ceb1) and retried. No valgrind errors and no segfault at least so far. Thanks.

**Comment by JonathanHenson** [comment]
great! Closing now. Reopen if you encounter the problem again.
