### ISSUE TITLE
Has this c++ sdk been proven to work with GovCloud?

### ISSUE THREAD

**Issue by haisamido** [awslabs/aws-sdk-cpp#102]
@awslabs 

Has this c++ sdk been proven to work with GovCloud's S3? If so what needs to be changed and specifically what should the `endPointOverride` be for GovCloud?  I ask because when it is set to `https://s3-us-gov-west-1.amazonaws.com/` the connection times out.

**Comment by JonathanHenson** [comment]
Did you also set "authenticationRegion" to us-gov-west-1?

**Comment by haisamido** [comment]
Yes. This is the returned message:

`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

The keys work from CLI and are the same ones that are used in the c++ code.  Printout of the keys from the c++ code shows that the keys match ones ones in the ./.aws/credentials file.  I wonder if the SDK doesn't "like" the generated keys!

**Comment by JonathanHenson** [comment]
Could i see the code where you constructing your client?

**Comment by haisamido** [comment]
Thank you for your reply.  Sill mistake there was an extra / that caused the problem.
