### ISSUE TITLE
iOS armv7

### ISSUE THREAD

**Issue by BruceSutherland** [awslabs/aws-sdk-cpp#104]
Hi,

I've tried using the C++ SDK with Unreal however I am receiving link errors when packaging my project.

It seems the library is missing symbols for armv7.

I used the following cmake command line:

cmake -DBUILD_ONLY="aws-cpp-sdk-cognito-identity" -DSTATIC_LINKING=1 -DTARGET_ARCH=APPLE -DCMAKE_BUILD_TYPE=Release

The OSX editor target is linking without issue.

Does the SDK support armv7 out of the box?

Does it support arm64?

Are there different settings I need on my command line to target iOS?

Thanks.

**Comment by JonathanHenson** [comment]
I haven't actually attempted arm yet except for android. I'd love to help you as you work through it.

**Comment by JonathanHenson** [comment]
In theory, it's just c++ 11, so it should work fine. Can you post the link errors. My guess is curl is the culprit.

**Comment by JonathanHenson** [comment]
I'm planning on adding NSUrl http implementation in the near future which will remove the issue if that is the problem.

**Comment by BruceSutherland** [comment]
Hi Jonathan,

Thanks very much for the speedy response.

These are the errors:

LogPlayLevel: mono: Undefined symbols for architecture armv7:
LogPlayLevel: mono:   "Aws::Client::ClientConfiguration::ClientConfiguration()", referenced from:
LogPlayLevel: mono:       ATheZooGameMode::ATheZooGameMode() in TheZooGameMode.cpp.o
LogPlayLevel: mono:   "Aws::CognitoIdentity::CognitoIdentityClient::CognitoIdentityClient(Aws::Client::ClientConfiguration const&)", referenced from:
LogPlayLevel: mono:       ATheZooGameMode::ATheZooGameMode() in TheZooGameMode.cpp.o
LogPlayLevel: mono:   "Aws::CognitoIdentity::CognitoIdentityClient::~CognitoIdentityClient()", referenced from:
LogPlayLevel: mono:       ATheZooGameMode::ATheZooGameMode() in TheZooGameMode.cpp.o
LogPlayLevel: mono: ld: symbol(s) not found for architecture armv7

I've never used CMake before so I think this isn't working because of something I may have missed.

When I built I executed the following commands:

cmake -DBUILD_ONLY="aws-cpp-sdk-cognito-identity" -DSTATIC_LINKING=1 -DTARGET_ARCH=APPLE -DCMAKE_BUILD_TYPE=Release
make

I then added the libraries I need to the Unreal engine.

The game is building fine for the OSX target, including linkage to libcurl and zlib without issue.

I understand that Apple has universal binaries and that code for multiple target architectures can be contained inside a single static library however I did at least expect to have a different library file for OSX and iOS.

I took a look inside the CMakeLists.txt file however I don't see anything that would suggest building with the iOS toolchain and SDK. I tried the following with no success:

Bruces-MBP:AWS-CPP-SDK Bruce$ cmake -DBUILD_ONLY="aws-cpp-sdk-cognito-identity" -DSTATIC_LINKING=1 -DTARGET_ARCH=APPLE -DCMAKE_BUILD_TYPE=Release **-DCMAKE_CXX_FLAGS="-arch armv7"**
-- Generating Mac OSX/IOS build config
-- Dynamic linking disabled
-- Custom memory management disabled
-- Http client: Curl
-- Encryption: CommonCrypto
-- Install binary prefix: mac
Updating version info to 0.9.6-13-g540b691
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK
Bruces-MBP:AWS-CPP-SDK Bruce$ make
Scanning dependencies of target aws-cpp-sdk-core
[  1%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp:16:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/AmazonSerializableWebServiceRequest.h:19:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h:20:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSFunction.h:20:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h:20:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:21:
In file included from /Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/include/aws/core/utils/memory/MemorySystemInterface.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:85:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/unistd.h:71:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture
#error Unsupported architecture

Any help you can provide to shed some light on how to build for iOS architectures would be greatly appreciated.

I even went to the lengths of generating the Xcode project and manually changing the schemes in Xcode however I ran into some trouble with the use of long instead of int and narrowing conversions causing build failures for arm64 builds.

At that point I guessed there was maybe something I was missing if the APPLE target should spit out iOS symbols.

Cheers,
Bruce

**Comment by BruceSutherland** [comment]
Hey Jonathan,

I started from scratch today and everything built just fine.

I generated the Xcode projects and changed the target SDK to iOS in Xcode, hit build and it's all OK.

I've no idea what I did wrong last week.

Sorry if I wasted any of your time :).

**Comment by jimbojr55** [comment]
iam"iam"
