### ISSUE TITLE
CloudWatch StatisticSet: floating point values are not correctly URL encoded

### ISSUE THREAD

**Issue by kevincdeng** [awslabs/aws-sdk-cpp#105]
https://github.com/awslabs/aws-sdk-cpp/blob/master/aws-cpp-sdk-monitoring/source/model/StatisticSet.cpp#L90

This produces output that looks like `StatisticValues.Sum=5.88181e+07`, which causes MalformedInput exception. The `+` should probably be encoded as `%2B`.

I'm currently working around it with this patch to remove the scientific notation:

```patch
--- PutMetricDataRequest.cpp  2016-02-11 16:12:59.000000000 -0800
+++ PutMetricDataRequest.2.cpp  2016-02-11 16:19:20.000000000 -0800
@@ -12,6 +12,8 @@
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
+#include <iomanip>
+
 #include <aws/monitoring/model/PutMetricDataRequest.h>
 #include <aws/core/utils/StringUtils.h>
 #include <aws/core/utils/memory/stl/AWSStringStream.h>
@@ -29,6 +31,7 @@
 {
   Aws::StringStream ss;
   ss << "Action=PutMetricData&";
+  ss << std::fixed << std::setprecision(std::numeric_limits<long double>::digits10 + 1);
   if(m_namespaceHasBeenSet)
   {
     ss << "Namespace=" << StringUtils::URLEncode(m_namespace.c_str()) << "&";
```

**Comment by JonathanHenson** [comment]
I can look at adding this to the generator in the morning. Thanks for the report.

**Comment by kevincdeng** [comment]
I'd try to stick to the scientific notation rather than using fixed precision since the latter can't represent all possible double values unless the number of digits is set to some extreme value. For example the number 1e-300 would need over 300 digits to represent accurately in fixed precision.

**Comment by JonathanHenson** [comment]
So the behavior of all of the other static language sdks is for everything less than 10^-3 and greater than 10^7 to be scientific notation. I will keep this behavior, but make sure it is URL encoded.

**Comment by JonathanHenson** [comment]
ok, give that a try. I think it should be good to go.

**Comment by kevincdeng** [comment]
Yup it's fine now, thanks!

```
StatisticValues.Sum=3.3535e%2B33
```
