### ISSUE TITLE
can not use AttributeValue.Set...

### ISSUE THREAD

**Issue by kyunbum9** [awslabs/aws-sdk-cpp#108]
Undefined symbols for architecture x86_64:
  "Aws::DynamoDB::Model::AttributeValue::SetS(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Aws::DynamoDB::Model::AttributeValue::SetS(char const*) in MyTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

platform: Mac (elcapitan)

**Comment by JonathanHenson** [comment]
If you built with the default cmake args, you need to pass -DAWS_CUSTOM_MEMORY_MANAGEMENT to your compile command.

**Comment by kyunbum9** [comment]
i maked 
cmake . -DCUSTOM_MEMORY_MANAGEMENT=1

it's creaeted dylib of mac (it'is dll)
but it's faild

Undefined symbols for architecture x86_64:
  "Aws::DynamoDB::Model::AttributeValue::SetN(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Aws::DynamoDB::Model::AttributeValue::SetN(char const*) in MyLogic.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JonathanHenson** [comment]
You need to pass the -DAWS_CUSTOM_MEMORY_MANAGEMENT flag to the compiler
for your application.

**Comment by kyunbum9** [comment]
$ cmake . -DAWS_CUSTOM_MEMORY_MANAGEMENT=1 -DSTATIC_LINKING=1

-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Generating Mac OSX/IOS build config
-- Dynamic linking disabled
-- Http client: Curl
-- Encryption: CommonCrypto
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install binary prefix: mac
-- Found Git: /usr/bin/git (found version "2.5.4 (Apple Git-61)") 
Updating version info to 0.9.6-33-g9718a74
-- Custom memory management disabled
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project: <--- not used

    AWS_CUSTOM_MEMORY_MANAGEMENT


-- Build files have been written to: /aws-sdk-cpp

**Comment by JonathanHenson** [comment]
No. Building the SDK and building YOUR application are two different
things. You have two options. Turn custom memory management off when you
build the SDK, then build as normal for your application. Or 2nd, build the
SDK with custom memory management, then you need to pass the
-DAWS_CUSTOM_MEMORY_MANAGEMENT flag to the compiler for YOUR application
(not the SDK)

On Sun, Feb 21, 2016 at 7:56 PM, 李均範 <notifications@github.com> wrote:

> $ cmake . -DAWS_CUSTOM_MEMORY_MANAGEMENT=1 -DSTATIC_LINKING=1
>
> -- TARGET_ARCH not specified; inferring host OS to be platform compilation
> target
> -- Generating Mac OSX/IOS build config
> -- Dynamic linking disabled
> -- Http client: Curl
> -- Encryption: CommonCrypto
> -- The C compiler identification is AppleClang 7.0.2.7000181
> -- The CXX compiler identification is AppleClang 7.0.2.7000181
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Install binary prefix: mac
> -- Found Git: /usr/bin/git (found version "2.5.4 (Apple Git-61)")
> Updating version info to 0.9.6-33-g9718a74
> -- Custom memory management disabled
> -- Configuring done
> -- Generating done
> CMake Warning:
> Manually-specified variables were not used by the project: <--- not used
>
> AWS_CUSTOM_MEMORY_MANAGEMENT
>
> -- Build files have been written to: /aws-sdk-cpp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-cpp/issues/108#issuecomment-186994046>
> .
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by kyunbum9** [comment]
thank u... :+1: 
i solved from your teach
you are genius!!
