### ISSUE TITLE
S3 GetObject w/curl doesn't work if key contains +

### ISSUE THREAD

**Issue by jbadorek** [awslabs/aws-sdk-cpp#110]
When trying to use GetObject on a file that has a + in it's path, a SignatureDoesNotMatch error is emitted. e.g.:

bucket: some-bucket
key: this+that/somefile.txt

The problem is if you url encode the key when populating GetObjectRequest to "this%2Bthat/somefile.txt", the signature no longer matches since S3 is expecting "this+that/somefile.txt". And if you don't url encode the key, curl treats the + as a space and thus a 404. I temporarily fixed it replacing all +'s with %2B in CurlHttpClient.cpp ~#168.

        Aws::Utils::StringUtils::Replace(url, "+", "%2B");
        curl_easy_setopt(connectionHandle, CURLOPT_URL, url.c_str());

**Comment by JonathanHenson** [comment]
Fixed in latest push.
