### ISSUE TITLE
Lots of pessimizing calls to std::move

### ISSUE THREAD

**Issue by Bu11etmagnet** [awslabs/aws-sdk-cpp#111]
aws-cpp-sdk-core/source/auth/AWSCredentialsProviderChain.cpp:29:20: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/include/aws/core/AmazonStreamingWebServiceRequest.h:48:16: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp:32:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp:118:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp:289:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/auth/AWSAuthSigner.cpp:341:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:258:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:351:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:412:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/logging/FormattedLogSystem.cpp:101:31: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/logging/FormattedLogSystem.cpp:111:31: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:57:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:68:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp:37:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:95:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:113:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp:217:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp:226:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:186:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/StringUtils.cpp:194:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
aws-cpp-sdk-core/source/utils/unix/FileSystemUtils.cpp:60:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]

$ git branch -v
* master 4b4873e Reverted accidental removal from access-management.

**Comment by JonathanHenson** [comment]
thanks for the callout. This has been updated in the latest push.
