### ISSUE TITLE
how can use in c++ builder?

### ISSUE THREAD

**Issue by yikyunbum** [awslabs/aws-sdk-cpp#112]

**Comment by JonathanHenson** [comment]
mkdir build
cd build
cmake -G "Borland Makefiles" <path-to-aws-sdk-for-c-source>

**Comment by yikyunbum** [comment]
C:\aws-sdk-cpp>cmake -G "Borland Makefiles" .
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Generating windows build config
-- Dynamic linking enabled
-- Http client: WinHttp
-- Encryption: Bcrypt
-- The C compiler identification is Embarcadero 7.10.8:7>
-- The CXX compiler identification is Embarcadero 7.10.8:7>
-- Check for working C compiler: C:/Program Files (x86)/Embarcadero/Studio/17.0/bin/bcc32.exe
-- Check for working C compiler: C:/Program Files (x86)/Embarcadero/Studio/17.0/bin/bcc32.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Embarcadero/Studio/17.0/bin/bcc32.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Embarcadero/Studio/17.0/bin/bcc32.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Install binary prefix: windows/ia32
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.7.0.windows.1")
Updating version info to 0.9.6-33-g9718a74
-- Custom memory management enabled; stl objects now using custom allocators
-- Configuring done
-- Generating done
-- Build files have been written to: C:/aws-sdk-cpp

C:\aws-sdk-cpp>make
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
Scanning dependencies of target aws-cpp-sdk-core
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.obj
Embarcadero C++ 7.10 for Win32 Copyright (c) 1993-2015 Embarcadero Technologies, Inc.
C:\aws-sdk-cpp\aws-cpp-sdk-core\source\AmazonSerializableWebServiceRequest.cpp:
Error E2451 C:/aws-sdk-cpp/aws-cpp-sdk-core/include\aws/core/utils/memory/MemorySystemInterface.h 38: Undefined symbol 'nullptr'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 385: Multiple declaration for 'char_traits<wchar_t>::int_type'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 136: Earlier declaration of 'char_traits<wchar_t>::int_type'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 391: Multiple declaration for 'char_traits<wchar_t>::assign(wchar_t &,const wchar_t &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 141: Earlier declaration of 'char_traits<wchar_t>::assign(wchar_t &,const wchar_t &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 396: Multiple declaration for 'char_traits<wchar_t>::eq(const wchar_t &,const wchar_t &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 146: Earlier declaration of 'char_traits<wchar_t>::eq(const wchar_t &,const wchar_t &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 401: Multiple declaration for 'char_traits<wchar_t>::lt(const wchar_t &,const wchar_t &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 151: Earlier declaration of 'char_traits<wchar_t>::lt(const wchar_t &,const wchar_t &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 407: Multiple declaration for 'char_traits<wchar_t>::compare(const wchar_t *,const wchar_t *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 156: Earlier declaration of 'char_traits<wchar_t>::compare(const wchar_t *,const wchar_t *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 414: Multiple declaration for 'char_traits<wchar_t>::length(const wchar_t *)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 167: Earlier declaration of 'char_traits<wchar_t>::length(const wchar_t *)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 421: Multiple declaration for 'char_traits<wchar_t>::copy(wchar_t *,const wchar_t *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 176: Earlier declaration of 'char_traits<wchar_t>::copy(wchar_t *,const wchar_t *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 429: Multiple declaration for 'char_traits<wchar_t>::find(const wchar_t *,unsigned int,const wchar_t &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 187: Earlier declaration of 'char_traits<wchar_t>::find(const wchar_t *,unsigned int,const wchar_t &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 436: Multiple declaration for 'char_traits<wchar_t>::move(wchar_t *,const wchar_t *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 197: Earlier declaration of 'char_traits<wchar_t>::move(wchar_t *,const wchar_t *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 443: Multiple declaration for 'char_traits<wchar_t>::assign(wchar_t *,unsigned int,wchar_t)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 212: Earlier declaration of 'char_traits<wchar_t>::assign(wchar_t *,unsigned int,wchar_t)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 454: Multiple declaration for 'char_traits<wchar_t>::to_int_type(const wchar_t &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 227: Earlier declaration of 'char_traits<wchar_t>::to_int_type(const wchar_t &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 465: Multiple declaration for 'char_traits<wchar_t>::eof()'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 238: Earlier declaration of 'char_traits<wchar_t>::eof()'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 486: Multiple declaration for 'char_traits<char>::assign(char &,const char &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 141: Earlier declaration of 'char_traits<char>::assign(char &,const char &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 491: Multiple declaration for 'char_traits<char>::eq(const char &,const char &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 146: Earlier declaration of 'char_traits<char>::eq(const char &,const char &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 496: Multiple declaration for 'char_traits<char>::lt(const char &,const char &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 151: Earlier declaration of 'char_traits<char>::lt(const char &,const char &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 502: Multiple declaration for 'char_traits<char>::compare(const char *,const char *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 156: Earlier declaration of 'char_traits<char>::compare(const char *,const char *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 509: Multiple declaration for 'char_traits<char>::length(const char *)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 167: Earlier declaration of 'char_traits<char>::length(const char *)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 516: Multiple declaration for 'char_traits<char>::copy(char *,const char *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 176: Earlier declaration of 'char_traits<char>::copy(char *,const char *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 524: Multiple declaration for 'char_traits<char>::find(const char *,unsigned int,const char &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 187: Earlier declaration of 'char_traits<char>::find(const char *,unsigned int,const char &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 531: Multiple declaration for 'char_traits<char>::move(char *,const char *,unsigned int)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 197: Earlier declaration of 'char_traits<char>::move(char *,const char *,unsigned int)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 538: Multiple declaration for 'char_traits<char>::assign(char *,unsigned int,char)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 212: Earlier declaration of 'char_traits<char>::assign(char *,unsigned int,char)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 549: Multiple declaration for 'char_traits<char>::to_int_type(const char &)'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 227: Earlier declaration of 'char_traits<char>::to_int_type(const char &)'
Error E2238 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 560: Multiple declaration for 'char_traits<char>::eof()'
Error E2344 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\iosfwd 238: Earlier declaration of 'char_traits<char>::eof()'
Error E2406 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\xutility 346: Dependent type qualifier 'bool' is not a class or struct type
Error E2406 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\xutility 347: Dependent type qualifier 'bool' is not a class or struct type
Error E2406 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\xutility 348: Dependent type qualifier 'bool' is not a class or struct type
Error E2228 C:\Program Files (x86)\Embarcadero\Studio\17.0\include\dinkumware\xutility 348: Too many error or warning messages
*** 51 errors in Compile ***

** error 2 ** deleting aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\source\AmazonSerializableWebServiceRequest.cpp.obj

** error 1 ** deleting aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\all

** error 1 ** deleting all

**Comment by JonathanHenson** [comment]
As for the first error, it looks like your build tool either doesn't know how or doesn't know to use the c++ 11 standard. Is there a flag that you pass to C++ Builder to tell it the standard level. e.g. --std=c++11?

The others are errors within the IDE itself.

**Comment by yikyunbum** [comment]
i include header in c++ builder
and compile this..

Compiling Project1.cbproj (Debug, Win64)
bcc64 command line for "Project1PCH1.h"
  c:\program files (x86)\embarcadero\studio\17.0\bin\bcc64.exe -cc1 -D _DEBUG -D USEPACKAGES -n .\Win64\Debug -I 
  C:\Users\Kyunbum\Documents\Embarcadero\Studio\Projects -I C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-dynamodb\include -I 
  C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-core\include -I "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\dinkumware64" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include\windows\crtl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\sdk" 
  -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\rtl" -isystem "c:\program files 
  (x86)\embarcadero\studio\17.0\include\windows\vcl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  C:\Users\Public\Documents\Embarcadero\Studio\17.0\hpp\Win64 -g -fno-limit-debug-info -fborland-extensions -nobuiltininc -nostdsysteminc -triple 
  x86_64-pc-win32-elf -emit-pch -fexceptions -fcxx-exceptions -fseh -munwind-tables -mstackrealign -fno-spell-checking -fno-use-cxa-atexit -x c++ 
  -std=c++11 -O0 -tR -tM -tU -tW -o .\Win64\Debug\Project1PCH1.pch Project1PCH1.h 
bcc64 command line for "Project1.cpp"
  c:\program files (x86)\embarcadero\studio\17.0\bin\bcc64.exe -cc1 -D _DEBUG -D USEPACKAGES -n .\Win64\Debug -I 
  C:\Users\Kyunbum\Documents\Embarcadero\Studio\Projects -I C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-dynamodb\include -I 
  C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-core\include -I "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\dinkumware64" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include\windows\crtl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\sdk" 
  -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\rtl" -isystem "c:\program files 
  (x86)\embarcadero\studio\17.0\include\windows\vcl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  C:\Users\Public\Documents\Embarcadero\Studio\17.0\hpp\Win64 -g -fno-limit-debug-info -fborland-extensions -nobuiltininc -nostdsysteminc -triple 
  x86_64-pc-win32-elf -emit-obj -fexceptions -fcxx-exceptions -fseh -munwind-tables -mstackrealign -fno-spell-checking -fno-use-cxa-atexit 
  -main-file-name Project1.cpp -x c++ -std=c++11 -O0 -tR -tM -tU -tW -o .\Win64\Debug\Project1.o -dependency-file .\Win64\Debug\Project1.d -MT 
  .\Win64\Debug\Project1.o -sys-header-deps -include-pch .\Win64\Debug\Project1PCH1.pch Project1.cpp 
bcc64 command line for "Unit1.cpp"
  c:\program files (x86)\embarcadero\studio\17.0\bin\bcc64.exe -cc1 -D _DEBUG -D USEPACKAGES -n .\Win64\Debug -I 
  C:\Users\Kyunbum\Documents\Embarcadero\Studio\Projects -I C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-dynamodb\include -I 
  C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-core\include -I "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\dinkumware64" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include\windows\crtl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\sdk" 
  -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\rtl" -isystem "c:\program files 
  (x86)\embarcadero\studio\17.0\include\windows\vcl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  C:\Users\Public\Documents\Embarcadero\Studio\17.0\hpp\Win64 -g -fno-limit-debug-info -fborland-extensions -nobuiltininc -nostdsysteminc -triple 
  x86_64-pc-win32-elf -emit-obj -fexceptions -fcxx-exceptions -fseh -munwind-tables -mstackrealign -fno-spell-checking -fno-use-cxa-atexit 
  -main-file-name Unit1.cpp -x c++ -std=c++11 -O0 -tR -tM -tU -tW -o .\Win64\Debug\Unit1.o -dependency-file .\Win64\Debug\Unit1.d -MT 
  .\Win64\Debug\Unit1.o -sys-header-deps -include-pch .\Win64\Debug\Project1PCH1.pch Unit1.cpp 
bcc64 command line for "Dyna.cpp"
  c:\program files (x86)\embarcadero\studio\17.0\bin\bcc64.exe -cc1 -D _DEBUG -D USEPACKAGES -n .\Win64\Debug -I 
  C:\Users\Kyunbum\Documents\Embarcadero\Studio\Projects -I C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-dynamodb\include -I 
  C:\Users\Kyunbum\Source\Repos\aws-sdk-cpp\aws-cpp-sdk-core\include -I "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\dinkumware64" -isystem 
  "c:\program files (x86)\embarcadero\studio\17.0\include\windows\crtl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\sdk" 
  -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\rtl" -isystem "c:\program files 
  (x86)\embarcadero\studio\17.0\include\windows\vcl" -isystem "c:\program files (x86)\embarcadero\studio\17.0\include\windows\fmx" -isystem 
  C:\Users\Public\Documents\Embarcadero\Studio\17.0\hpp\Win64 -g -fno-limit-debug-info -fborland-extensions -nobuiltininc -nostdsysteminc -triple 
  x86_64-pc-win32-elf -emit-obj -fexceptions -fcxx-exceptions -fseh -munwind-tables -mstackrealign -fno-spell-checking -fno-use-cxa-atexit 
  -main-file-name Dyna.cpp -x c++ -std=c++11 -O0 -tR -tM -tU -tW -o .\Win64\Debug\Dyna.o -dependency-file .\Win64\Debug\Dyna.d -MT .\Win64\Debug\Dyna.o 
  -sys-header-deps -include-pch .\Win64\Debug\Project1PCH1.pch Dyna.cpp 
[bcc64 Error] Array.h(58): use of undeclared identifier 'stdext'
[bcc64 Error] Array.h(58): 'T' does not refer to a value
  Array.h(38): declared here
[bcc64 Error] Array.h(58): expected expression
[bcc64 Error] Array.h(75): use of undeclared identifier 'stdext'
[bcc64 Error] Array.h(75): 'T' does not refer to a value
  Array.h(38): declared here
[bcc64 Error] Array.h(75): expected expression
[bcc64 Error] Array.h(105): use of undeclared identifier 'stdext'
[bcc64 Error] Array.h(105): 'T' does not refer to a value
  Array.h(38): declared here
[bcc64 Error] Array.h(105): expected expression
[bcc64 Error] ComparisonOperator.h(30): expected '}'
  ComparisonOperator.h(26): to match this '{'



becase
  #ifdef _WIN32  <----- this....compile 
                std::copy( other.m_data.get(), other.m_data.get() + other.m_size, stdext::checked_array_iterator< T * >( m_data.get(), m_size ) );
            #else
                std::copy(other.m_data.get(), other.m_data.get() + other.m_size, m_data.get());
            #endif // MSVC
        }


c++ builder not have stdext

**Comment by bretambrose** [comment]
What happens if you change the _WIN32 to _MSC_VER

**Comment by kyunbum9** [comment]
i set c++ builder  std=c++11

c++ builder default _WIN32 define
i not change..
