### ISSUE TITLE
S3 path key with space not handled correctly

### ISSUE THREAD

**Issue by patilarpith** [awslabs/aws-sdk-cpp#113]
Lets say I'm trying to fetch from S3 Path: ```s3://my-bucket/unit-tests/New folder/hello.txt```

Without any explicit URL encoding if I set the following values and do a s3_get(), the result is ``` No response body.  Response code: 505```
```cpp
S3::Model::GetObjectRequest Request;
Request.SetBucket(s3_bucket); // -> my-bucket
Request.SetKey(s3_key); // unit-tests/New folder/hello.txt
```

With explicit URL encoding if I set the following values and do a s3_get(), the result is ```No response body.  Response code: 403```
```cpp
S3::Model::GetObjectRequest Request;
Request.SetBucket(s3_bucket); // -> my-bucket
Request.SetKey(s3_key); // unit-tests/New%20folder/hello.txt
```
Found a similar issue in aws-php sdk which was fixed. Could even the cpp sdk also be suffering from the same?
https://github.com/aws/aws-sdk-php/issues/37

**Comment by JonathanHenson** [comment]
What revision are your running against? We do explicitly URL encode the path and this works on my machine. Please provide more details.

**Comment by JonathanHenson** [comment]
closing because, we've already fixed this. Haven't recieved confirmation from this user, feel free to open if issue is encountered again.

**Comment by patilarpith** [comment]
Sorry for the delayed response. I believe the issue was in 0.9.6 release. Tested again on the latest master and everything works fine.
