### ISSUE TITLE
What headers in include?

### ISSUE THREAD

**Issue by Stargx** [awslabs/aws-sdk-cpp#116]
Hi,
I've downloaded and built the SDK. I'm now trying to use some of the example code as a test in my project. Like this:

`Aws::DynamoDB::DynamoDBClient dynamoDbClient;
PutItemRequest putItemRequest;
putItemRequest.WithTableName("TestTableName");
AttributeValue hashKeyAttribute;
hashKeyAttribute.SetS("SampleHashKeyValue");
putItemRequest.AddItem("HashKey", hashKeyAttribute);
AttributeValue valueAttribute;
valueAttribute.SetS("SampleValue");
putItemRequest.AddItem("Value", valueAttribute);
auto putItemOutcome = dynamoDbClient.PutItem(putItemRequest);

if(putItemOutcome.IsSuccess())
{
    std::cout << "PutItem Success Using IOPS " << putItemOutcome.GetResult().GetConsumedCapacity();
}
else
{
    std::cout << "PutItem failed with error " << putItemOutcome.GetError().GetMessage();
}`

However, I can't find anywhere that tells you what headers to include. I've tried it, but I just seem to end up with a longer and longer list of headers.

Any tips?

Cheers,
Steve

**Comment by JonathanHenson** [comment]
Start with

<aws/dynamodb/DynamoDBClient.h>

There are several forward declarations in that file, but their fully
qualified type names and header paths are very closely related.
