### ISSUE TITLE
Glacier UploadArchive returns Missing Parameter (API Version)

### ISSUE THREAD

**Issue by sploggy** [awslabs/aws-sdk-cpp#117]
```
Aws::Glacier::Model::UploadArchiveRequest req;
req.SetVaultName(my_vaultname);
req.SetArchiveDescription(my_description);
req.SetChecksum(treehash);

req.SetBody(Aws::MakeShared<Aws::FStream>(NULL, path, std::ios::in));

auto outcome = my_glacier_client->UploadArchive(req);
```

I get a HTTP 400 response that decodes as MissingParameterValueException (Required parameter missing: API version). Looking through the trace I can't see any reference to x-amz-glacier-version being sent.

Am I doing something wrong?

**Comment by JonathanHenson** [comment]
You are not doing anything wrong, we need to add some customizations to the glacier client.

**Comment by JonathanHenson** [comment]
Fixed in latest push.
