### ISSUE TITLE
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]

### ISSUE THREAD

**Issue by haisamido** [awslabs/aws-sdk-cpp#119]
I get the below errors when I do this (g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4. CentOS7)

```
git clone https://github.com/awslabs/aws-sdk-cpp.git
cd aws-sdk-cpp/
mkdir ./Release
cd ./Release/
cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_LINKING=0 -DCUSTOM_MEMORY_MANAGEMENT=0 ../
make

```

errors:

```
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function ‘virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::Sha256HMACOpenSSLImpl::Calculate(const ByteBuffer&, const ByteBuffer&)’:
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:115:14: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined
     HMAC_CTX ctx;
              ^
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:116:23: error: ‘HMAC_CTX_init’ was not declared in this scope
     HMAC_CTX_init(&ctx);
                       ^
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:121:26: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
     HMAC_CTX_cleanup(&ctx);
                          ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/crypto/openssl/CryptoImpl.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
```

**Comment by JonathanHenson** [comment]
It looks like you are missing the openssl headers (and likely curl as well) can you install the dev packages for your distrobution and try again?

**Comment by haisamido** [comment]
They're installed unless the headers are on in the -devel and/or -libs packages:

```
sudo yum list installed | grep -i openssl
openssl.x86_64                         1:1.0.1e-51.el7_2.2             @updates 
openssl-devel.x86_64                   1:1.0.1e-51.el7_2.2             @updates 
openssl-libs.x86_64                    1:1.0.1e-51.el7_2.2             @updates 
openssl098e.x86_64                     0.9.8e-29.el7.centos.2          @base    
pyOpenSSL.x86_64                       0.13.1-3.el7                    @anaconda
```


```
yum list installed | grep -i 'curl'
curl.x86_64                            7.29.0-25.el7.centos            @base    
libcurl.x86_64                         7.29.0-25.el7.centos            @base    
libcurl-devel.x86_64                   7.29.0-25.el7.centos            @base    
python-pycurl.x86_64                   7.19.0-17.el7                   @anaconda
```

**Comment by JonathanHenson** [comment]
what about 
ls /usr/include | grep -i openssl

**Comment by haisamido** [comment]
```
tree /usr/include/openssl/
/usr/include/openssl/
├── aes.h
├── asn1.h
├── asn1_mac.h
├── asn1t.h
├── bio.h
├── blowfish.h
├── bn.h
├── buffer.h
├── camellia.h
├── cast.h
├── cmac.h
├── cms.h
├── comp.h
├── conf_api.h
├── conf.h
├── crypto.h
├── des.h
├── des_old.h
├── dh.h
├── dsa.h
├── dso.h
├── dtls1.h
├── ebcdic.h
├── ecdh.h
├── ecdsa.h
├── ec.h
├── engine.h
├── e_os2.h
├── err.h
├── evp.h
├── fips.h
├── fips_rand.h
├── hmac.h
├── idea.h
├── krb5_asn.h
├── kssl.h
├── lhash.h
├── md2.h
├── md4.h
├── md5.h
├── modes.h
├── objects.h
├── obj_mac.h
├── ocsp.h
├── opensslconf.h
├── opensslconf-x86_64.h
├── opensslv.h
├── ossl_typ.h
├── pem2.h
├── pem.h
├── pkcs12.h
├── pkcs7.h
├── pqueue.h
├── rand.h
├── rc2.h
├── rc4.h
├── ripemd.h
├── rsa.h
├── safestack.h
├── seed.h
├── sha.h
├── srtp.h
├── ssl23.h
├── ssl2.h
├── ssl3.h
├── ssl.h
├── stack.h
├── symhacks.h
├── tls1.h
├── ts.h
├── txt_db.h
├── ui_compat.h
├── ui.h
├── whrlpool.h
├── x509.h
├── x509v3.h
└── x509_vfy.h

0 directories, 77 files

```

**Comment by JonathanHenson** [comment]
ok...

these:
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function ‘virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::Sha256HMACOpenSSLImpl::Calculate(const ByteBuffer&, const ByteBuffer&)’:
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:115:14: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined
     HMAC_CTX ctx;
              ^
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:116:23: error: ‘HMAC_CTX_init’ was not declared in this scope
     HMAC_CTX_init(&ctx);
                       ^
/home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:121:26: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
     HMAC_CTX_cleanup(&ctx);
                          ^

make no sense.

As for the warning. Try removing the -Wno-unused-private-field from your CMake. If memory serves me, that's a clang specific argument.

**Comment by JonathanHenson** [comment]
Ah

https://www.openssl.org/docs/manmaster/crypto/hmac.html

Looks like the way I'm using open ssl is deprecated. What version of openssl are you on?

**Comment by haisamido** [comment]
Here are the versions

```
sudo yum list installed | grep -i openssl
openssl.x86_64                         1:1.0.1e-51.el7_2.2             @updates 
openssl-devel.x86_64                   1:1.0.1e-51.el7_2.2             @updates 
openssl-libs.x86_64                    1:1.0.1e-51.el7_2.2             @updates 
openssl098e.x86_64                     0.9.8e-29.el7.centos.2          @base    
pyOpenSSL.x86_64                       0.13.1-3.el7                    @anaconda
```


```
yum list installed | grep -i 'curl'
curl.x86_64                            7.29.0-25.el7.centos            @base    
libcurl.x86_64                         7.29.0-25.el7.centos            @base    
libcurl-devel.x86_64                   7.29.0-25.el7.centos            @base    
python-pycurl.x86_64                   7.19.0-17.el7                   @anaconda
```

**Comment by JonathanHenson** [comment]
Well crap. You care to play around with the new API calls into openssl? I can probably get this out to you sometime this week.

**Comment by haisamido** [comment]
I just discovered the reason.  gflags from epel was installed.   Once I did `sudo yum erase gflags` I get past this error!

**Comment by JonathanHenson** [comment]
Great. I'll update the openssl implementation regardless and update the gcc builds to not include the clang only warning. I'll keep you updated.

**Comment by Bu11etmagnet** [comment]
GCC (5.3 at least) supports the -Wno-unused-private-field

**Comment by haisamido** [comment]
@JonathanHenson thank you for your help.  I do have one comment.  There may be a memory leak in compilation because it will fail randomly with "internal compiler error" so I have to compiled on an instance with more cores and RAM.

**Comment by gabrielfalcao** [comment]
> ok...
> 
> these: /home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function ‘virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::Sha256HMACOpenSSLImpl::Calculate(const ByteBuffer&, const ByteBuffer&)’: /home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:115:14: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined HMAC_CTX ctx; ^ /home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:116:23: error: ‘HMAC_CTX_init’ was not declared in this scope HMAC_CTX_init(&ctx); ^ /home/haisamido/Development/staging/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:121:26: error: ‘HMAC_CTX_cleanup’ was not declared in this scope HMAC_CTX_cleanup(&ctx); ^
> 
> make no sense.
> 
> As for the warning. Try removing the -Wno-unused-private-field from your CMake. If memory serves me, that's a clang specific argument.

---
1

so...

considering the build env, switching from gcc12 to clang is a bit helpful when a similar issue occurs while installing the test-depentencies of watchdog

```
$ uname -a
Darwin A13591.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64 arm Darwin
```

also unsetting CFLAGS was helpful since mine appears to be cluttered with homebrew+pkg-config+whatever I could do at present to use the apparent Apple Silicon equivalent of GNU/Debian's [build-essential](https://packages.debian.org/bullseye/build-essential)

```
export CC=$(which clang)
export CXX=$(which clang++)
```

the journey continue...
