### ISSUE TITLE
Link errors

### ISSUE THREAD

**Issue by Bu11etmagnet** [awslabs/aws-sdk-cpp#120]
$ git show --summary
commit 3fe46f05d1c58fc946045d3b860a79c88d76ceb1
Author: Jonathan M. Henson <henso@amazon.com>
Date:   Fri Feb 26 17:30:38 2016 -0800

    Added global to dll export definition.

$ ninja -j8 -k0
...
```
[503/509] Linking CXX executable aws-cpp-sdk-dynamodb-integration-tests/runDynamoDBIntegrationTests
FAILED: : && /home/csabaraduly/bin/g++-530-compat   -pedantic -Wextra -Wall -Werror -Wno-unused-private-field -pedantic -Wextra -fno-exceptions   aws-cpp-sdk-dynamodb-integration-tests/CMakeFiles/runDynamoDBIntegrationTests.dir/RunTests.cpp.o aws-cpp-sdk-dynamodb-integration-tests/CMakeFiles/runDynamoDBIntegrationTests.dir/TableOperationTest.cpp.o  -o aws-cpp-sdk-dynamodb-integration-tests/runDynamoDBIntegrationTests  -rdynamic aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.so testing-resources/libtesting-resources.so aws-cpp-sdk-core/libaws-cpp-sdk-core.so -lpthread -lssl -lcrypto -lz -lcurl -Wl,-rpath,/home/csabaraduly/workspace/aws-sdk-cpp-awslabs/__build_gcc530/aws-cpp-sdk-dynamodb:/home/csabaraduly/workspace/aws-sdk-cpp-awslabs/__build_gcc530/testing-resources:/home/csabaraduly/workspace/aws-sdk-cpp-awslabs/__build_gcc530/aws-cpp-sdk-core && :
aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.so: undefined reference to `Aws::Utils::EnumParseOverflowContainer::StoreOverflow(int, std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const&)'
aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.so: undefined reference to `Aws::Utils::EnumParseOverflowContainer::RetrieveOverflow(int) const'
aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.so: undefined reference to `Aws::g_enumOverflow'
collect2: error: ld returned 1 exit status

```

**Comment by JonathanHenson** [comment]
If you remove the extern keyword from /aws/core/Globals.h  what happens?

**Comment by JonathanHenson** [comment]
Actually, I don't feel like fighting the way globals work across platforms. I'm going to move the interface on this to a method and just do a static in the implementation. I know that will work across all linkers and will make the memory fencing easier.

In the meantime, I'm curious why this doesn't work for you as is. My gcc 4.9. builds work fine. I'd love some details for my own benefit.

**Comment by JonathanHenson** [comment]
I just pushed a fix out for this give it a try and let me know if you have any trouble.

**Comment by Bu11etmagnet** [comment]
> If you remove the extern keyword from /aws/core/Globals.h what happens?

Lots of "multiple definition of `Aws::g_enumOverflow' " link errors.

**Comment by Bu11etmagnet** [comment]
Do you want something like `debug_new_counter_t` from : https://github.com/eclipse/titan.core/blob/master/common/dbgnew.hh and https://github.com/eclipse/titan.core/blob/master/common/new.cc ?

**Comment by JonathanHenson** [comment]
I already fixed this. If it doesnt compile and link now, something else is
the problem.

**Comment by JonathanHenson** [comment]
Can you confirm that with yesterday's push, you can now build?

**Comment by Bu11etmagnet** [comment]
All builds fine at d48e71bd4221a880a3601a472096181c1e69b858
