### ISSUE TITLE
UploadRequest to Glacier fails with BadRequest

### ISSUE THREAD

**Issue by sploggy** [awslabs/aws-sdk-cpp#121]
Thanks for sorting #117, but now I get a BadRequest error.

Trace output (sanitised)

`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] Making request to https://glacier.eu-west-1.amazonaws.com/vaults/myvault/archives`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] Including headers:`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] authorization: AWS4-HMAC-SHA256 Credential=A*******************/20160304/eu-west-1/glacier/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-archive-description;x-amz-content-sha256;x-amz-date;x-amz-glacier-version;x-amz-sha256-tree-hash, Signature=4d************************************************************b0`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] content-length: 364960`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] content-type: binary/octet-stream`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] host: glacier.eu-west-1.amazonaws.com`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] user-agent: aws-sdk-cpp/0.9.6-67-g3f84fee Linux/4.1.12 x86_64`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] x-amz-archive-description: mydescription`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] x-amz-content-sha256: b3************************************************************02`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] x-amz-date: 20160304T225831Z`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] x-amz-glacier-version: 2012-06-01`
`[TRACE] 2016-03-04 22:58:31 CurlHttpClient [139819415877376] x-amz-sha256-tree-hash: b3************************************************************02`

According to http://docs.aws.amazon.com/amazonglacier/latest/dev/api-archive-post.html we should have something approaching:

**`POST /AccountId/vaults/VaultName/archives`**   (1)
`Host: glacier.Region.amazonaws.com`
`x-amz-glacier-version: 2012-06-01`
**`Date: Date`** (2)
`Authorization: SignatureValue`
`x-amz-archive-description: Description`
`x-amz-sha256-tree-hash: SHA256 tree hash`
`x-amz-content-sha256: SHA256 linear hash`
`Content-Length: Length`

`<Request body.>`

(1) Is the AccountID or '-' missing?
(2) Trace has 'x-amz-date' rather than 'Date' (although there is an example given further down the page that uses 'x-amz-Date')

Thanks!

**Comment by JonathanHenson** [comment]
x-amz-date and Date are interchangable.

Still investigating the AccountID portion.

**Comment by JonathanHenson** [comment]
according to the source code, AccountId would be there if you specified it. Did you specify it?

**Comment by sploggy** [comment]
Oops. My bad :(

All working now!
