### ISSUE TITLE
[Question] Is there a plan for a python interface to this?

### ISSUE THREAD

**Issue by thehesiod** [awslabs/aws-sdk-cpp#122]
That would be really really cool to speed up performance, and perhaps have a common core across languages.

Reason why I'm so interested is that in our application we need to update millions of files as quickly as possible.  I'm currently using aiohttp + botocore v4 auth, and between the overhead of the two I'm limited to ~25 concurrent requests per process and coming from c++ land I know it could do much much more :)

Let me know if I can help!

**Comment by JonathanHenson** [comment]
Why not use the python sdk to begin with?

**Comment by thehesiod** [comment]
from my experiments the python SDK (botocore/boto3) is too slow.  There's too much overhead. I switched to aiobotocore however its also ~25% slower than going raw aiohttp with botocore auth.

**Comment by JonathanHenson** [comment]
I suppose the first step is a c-style wrapper. I need to do that anyways. I
can certainly add that to the backlog.

**Comment by thehesiod** [comment]
cool!  will be exciting :)  could you ping me when that happens? closing this since answered.

**Comment by thehesiod** [comment]
btw, I don't think you need c bindings: https://gist.github.com/tonyseek/7821993

**Comment by thehesiod** [comment]
I think you may not have to write c bindings: https://wiki.python.org/moin/boost.python/SimpleExample.  There seem to be various tools available to wrap c++ methods.

**Comment by JonathanHenson** [comment]
extern "C"

{

    extern void cffi_hello(char *name)

    {

        return hello(name);

    }

}

Thats a c binding.

**Comment by thehesiod** [comment]
sorry, sent wrong example, updated with c++

**Comment by JonathanHenson** [comment]
I like this, boost is a bit of a show stopper for us, but maybe the
dependency is a single header file and in that case, it may work.

**Comment by thehesiod** [comment]
check this out: https://github.com/pybind/pybind11 <https://github.com/pybind/pybind11>

found it from this thread: http://stackoverflow.com/questions/13990317/generate-python-bindings-what-methods-programs-to-use <http://stackoverflow.com/questions/13990317/generate-python-bindings-what-methods-programs-to-use>

btw let me know if I'm pestering too much :)

**Comment by JonathanHenson** [comment]
Thats interesting. I wonder how this works with inheritance and
polymorphism. I need a c binding anyways, but the python port would be
better if it could hook directly in to the OOP code of c++.

**Comment by thehesiod** [comment]
http://pybind11.readthedocs.org/en/latest/classes.html#inheritance <http://pybind11.readthedocs.org/en/latest/classes.html#inheritance>
http://pybind11.readthedocs.org/en/latest/advanced.html#overriding-virtual-functions-in-python <http://pybind11.readthedocs.org/en/latest/advanced.html#overriding-virtual-functions-in-python>

https://github.com/pybind/pybind11/issues/105 <https://github.com/pybind/pybind11/issues/105>
from what I gather casting up is possible, not not down, yet

**Comment by prestomation** [comment]
Hi @thehesiod,
Have you benchmarked this C++ SDK with the same test cases that you used to determine that botocore is too slow for you?

We would love to see your test cases and performance metrics to understand that this SDK would actually be faster for you.

**Comment by JonathanHenson** [comment]
I think that's a great idea. Make sure you trst using async methods so io
latency doesn't skew the results as much.

**Comment by thehesiod** [comment]
@prestomation I have not yet, I was assuming the c++ libs would be faster :)  Basically my test was going to be writing a simple wrapper around the c++ lib to do the test.  If I get around to it I'll report back. thanks for the time guys!
