### ISSUE TITLE
Unable to build a simple S3 Client

### ISSUE THREAD

**Issue by satyenr** [awslabs/aws-sdk-cpp#14]
While trying to build a simple S3 client similar to one presented at [AWS Blog](https://aws.amazon.com/blogs/aws/introducing-the-aws-sdk-for-c/), I am getting the following error:

```
test.cxx:6:35: error: variable has incomplete type 'Aws::S3::Model::GetObjectRequest'
        Aws::S3::Model::GetObjectRequest getObjectRequest;
                                         ^
/home/satyenr/github/aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/S3Client.h:128:15: note: forward declaration of 'Aws::S3::Model::GetObjectRequest'
        class GetObjectRequest;
              ^
```

Here is the code snippet that is throwing the error:

```c++
	Aws::S3::S3Client s3Client;
	Aws::S3::Model::GetObjectRequest getObjectRequest;
	getObjectRequest.SetBucket("test-bucket");
	getObjectRequest.SetKey("test.txt");
```

Am I missing something here?

Additionally, some explanation of ALLOCATION_TAG would be really helpful.

Is there any documentation or examples that I can use to explore this further?

**Comment by satyenr** [comment]
I am using clang 3.4.2 on RHEL 7, if that matters.

```
shell> clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
shell>
```

**Comment by JonathanHenson** [comment]
Incomplete definition means there is a forward declaration and no formal
definition of the class that has been included.

You need to

#include <aws/s3/model/GetObjectRequest.h>

For our custom memory management  api, you pass an allocation tag if you
want to track your memory usage. It can be anything you want. I usually use
the fully qualified typename.

**Comment by satyenr** [comment]
Thanks @JonathanHenson! I should have spotted that. I am returning to C++ after a long time and I guess my C++ skills have dulled a bit. :-(

Is the SDK documented anywhere? Even a beta version of the documentation would do. I can certainly dig around in the source code to figure things out, but documentation would make like a little easier. :-)

Thanks again!

**Comment by JonathanHenson** [comment]
No problem, the number of c++ experts in the world == the standards
committee. The rest of us mere mortals are just hacks.

There is some documentation of core features in the readme. The
documentation for each api (e.g. s3, dynamodb etc...) is in the header
files for those clients and the models.

We are considering adding  doxygen generation in the near future.

**Comment by satyenr** [comment]
> We are considering adding  doxygen generation in the near future.

That would be great! Thanks again.
