### ISSUE TITLE
How to build the SDK with debugging symbols ?

### ISSUE THREAD

**Issue by bu2** [awslabs/aws-sdk-cpp#15]
Hi,

Any hint to build the SDK with debugging symbols ?
Specifically on OS X with clang ?

Regards,

Bruno.

**Comment by JonathanHenson** [comment]
When you compile a library using clang or gcc in debug, the debug symbols are part of the .so or .dylib assembly.

I haven't personally used XCode with this project. You might want to try out CLion, which I've been using with great success on OSX if you are having too much trouble connecting to a debugger. the only limitation is that it only uses CMake, so you would need to use CMake to make it work.

**Comment by bu2** [comment]
Thanks Jonathan,

I was able to build the SDK with debugging symbols (on OS X Yosemite 10.10.5, Xcode 7, Apple LLVM version 7.0.0 (clang-700.0.72), Target: x86_64-apple-darwin14.5.0) by using the following CMake command:

$ cmake -DCMAKE_CXX_FLAGS="-g" -DCMAKE_SHARED_LINKER_FLAGS="-g" -DCMAKE_STATIC_LINKER_FLAGS="-g" ..

So we can close this issue... but I am on the point to open a new one because I am investigating a "segmentation fault" which pop out in the SDK...

Regards.
