### ISSUE TITLE
CMake Errors During Configuration

### ISSUE THREAD

**Issue by jarruda** [awslabs/aws-sdk-cpp#20]
When configuring the project using a recent version of CMake (tested with 3.3.1 and 3.3.2), lots of errors are reported.

`> cmake .. -G "Visual Studio 12 Win64"`

```
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_FLAGS_DEBUGOPT
```

This error is repeated maybe 30 times, then it alternates:

```
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_EXE_LINKER_FLAGS_DEBUGOPT
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_FLAGS_DEBUGOPT
```

The project seems to build fine following this.  The issue is that when using the project through CMake's ExternalProject_Add, where these errors are treated like compile errors and fail any dependent projects.

**Comment by JonathanHenson** [comment]
I noticed this when writing some CI pipelines up today. My work around, since it caused Jenkins to falsely report an error was to pass arguments like -DCMAKE_EXE_LINKER_FLAGS_DEBUGOPT="" etc.... to my cmake command. I'll research more on this and come up with a more permanent solution shortly.

**Comment by jarruda** [comment]
That workaround worked great, thanks.

Might be worthwhile to submit a bug over at https://public.kitware.com/Bug/my_view_page.php and point them at this project?

**Comment by boinst** [comment]
I observed this same issue using CMAKE 3.5.0 RC1. Thanks for the workaround.

**Comment by DraconPern** [comment]
As others have mentioned before passing -DCMAKE_EXE_LINKER_FLAGS_DEBUGOPT="" -DCMAKE_CXX_FLAGS_DEBUGOPT=""  to CMAKE fixed the issue for me on VS2015

**Comment by JonathanHenson** [comment]
I pushed an update recently to automatically add this to the configuration if it hasn't been set. It should no longer be necessary to specify these arguments.
