### ISSUE TITLE
[Question] Thread Safety

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#24]
Hi, I am unsure where else may be a more appropriate place to ask this question.  What assumptions/expectations should I have regarding thread safety.  And, are methods comment decorated with such specifications anywhere?

Particularly I am concerned with the various Factory classes.

Thanks.

**Comment by JonathanHenson** [comment]
Everything in the sdk is designed with thread safety in mind and can be
used across threads safely. One cavaiate is it is your responsibility to
handle data classes safely if you mutate them when you are handling them
across threads (e.g. httprequests, responses, or the plain data objects
used for request and result processes)

**Comment by JonathanHenson** [comment]
I'll add, if you override any factories, it is your responsibility to implement your own code in a thread safe manner.

**Comment by cjhanks** [comment]
Is the library still considered "thread safe" with user space context switching (green threads)?  Or is it only thread safe given hardware concurrency?

**Comment by JonathanHenson** [comment]
I'm not sure I understand your question. Yes it is thread safe, but I"m not sure what you mean about the difference (from an application's point of view) between context switching and hardware concurency. There are proper memory fences in place to protect your data accross threads.
