### ISSUE TITLE
HttpClient::MakeRequest(shared_ptr<HttpRequest>) Can return Null SharedPtr, but why?

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#25]
It is possible (it happened to me anyways) for calls to the HttpClient to return a shared_ptr<HttpResponse> which is null with no apparent error being set in the library.  Recreating the case may be a little difficult (it's deep in my code).

https://github.com/awslabs/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L153

```C++
    CURL* connectionHandle = m_curlHandleContainer.AcquireCurlHandle();

    if (connectionHandle)
    {
    /// snip
    }
    // No else clause, no error set!
```

Apparently the m_curlHandleContainer is returning a null handle.  Why might that be and what information would be useful for you in debugging?

**Comment by JonathanHenson** [comment]
Thanks for the update. The logs would be very helpful. Also information on your build system and build commands as well as your platform information would be great.

**Comment by JonathanHenson** [comment]
Anyways, the direct answer is, yes, the http clients can return nullptr, and this is expected behavior for the contract. You should be checking the httpresponse ptr before using it.

**Comment by cjhanks** [comment]
It appears that a null shared_ptr is returned by MakeRequest if the request URL is malformed.  I will handle null response code appropriately.

```
[INFO] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Intializing CurlHandleContainer with size 25.
[INFO] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Initializing Curl library
[TRACE] 2015-10-05 16:38:09 CurlHttpClient [140028975368128] Making request to http:///api/rest/v1/ama/uuid/568a249f-45bb-401e-90bc-a221c1c492e1/poseVersions
[TRACE] 2015-10-05 16:38:09 CurlHttpClient [140028975368128] Including headers:
[TRACE] 2015-10-05 16:38:09 CurlHttpClient [140028975368128] host: 
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Attempting to acquire curl connection.
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] No current connections available in pool. Attempting to create new connections.
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] attempting to grow pool size by 2.
[INFO] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Pool successfully grown by 2
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Returning connection handle 0x1b4f1a0.
[DEBUG] 2015-10-05 16:38:09 CurlHttpClient [140028975368128] Obtained connection handle 0x1b4f1a0.
[ERROR] 2015-10-05 16:38:09 CurlHttpClient [140028975368128] Curl returned error code 6.
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Releasing curl handle 0x1b4f1a0.
[DEBUG] 2015-10-05 16:38:09 CurlHandleContainer [140028975368128] Notifying waiting threads.
```

Sorry to bother with all these reports, I hope my reports help in someone's google experience.
