### ISSUE TITLE
DefaultLogSystem constructor makes it hard to log to stderr

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-sdk-cpp#30]
For my testing program, I would like to log to stderr. The signature of DefaultLogSystem makes that quite hard though.

I would like to just plug in a pointer/reference to `std::cerr`, but according to the constructor it must be wrapped inside a `shared_ptr`.

For obvious reasons, I can't put `std::cerr` into a smart pointer or my program will segfault.

I tried making a wrapper object using Boost.Iostreams but for some reason that has a `static_assert` saying that I'm not allowed to wrap any of the built-in streams.

It would be good if there was a constructor where I could just pass in a naked pointer (or you supply an object that I can construct and pass that wraps another `std::ostream`).

**Comment by cjhanks** [comment]
What about making the shared_ptr deleter a noop?

**Comment by JonathanHenson** [comment]
Bret did something like you are trying to do in the android tests. I'm not
by a computer at the moment but you may want to have a look at that. I'll
have a look as soon as I make it to my machine.

**Comment by rix0rrr** [comment]
Doh, that's a simple solution.

Still doesn't feel *quite* right but at least it gets me out of a slump right now :). Thanks
