### ISSUE TITLE
Please export() the CMake targets and add include directories to them

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-sdk-cpp#31]
Hi,

I'd like to consume the SDK from my own CMake project without having to install it (I *detest* having to install libraries into my global system directories just to compile against them).

Fortunately, CMake makes it quite easy to consume a library that's also built with CMake from its build directory, if you prep the CMakeLists file correctly.

I'd just need two things:

* Specify the include directories for each module--and I could live without those because I can fix those in my *own* CMakeLists file.
* But the thing that I really need, is that you `export()` the targets in your top-level CMakeLists file.

The command looks like this:

    export(TARGETS
        aws-cpp-sdk-s3
        aws-cpp-sdk-core
        ...
        FILE AwsCppSdkConfig.cmake)

Given this, if I build my project with:

    cmake -DAwsCppSdk_DIR=/path/to/aws-sdk-cpp/build

Then in my own CMake file I can do this:

    find_package(AwsCppSdk)
    # Fix up the include directories of the targets that I found (wouldn't need to do this if you did it)
    set_property(TARGET aws-cpp-sdk-core PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${AwsCppSdk_DIR}/../aws-cpp-sdk-core/include)
    set_property(TARGET aws-cpp-sdk-s3 PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${AwsCppSdk_DIR}/../aws-cpp-sdk-s3/include)
    
And now I can simply `target_link_libraries` against the libraries without having to specify anything else (transitive include and linker dependencies will be taken care of for me by CMake). 

I'm in the process of compiling a guide to the most effective CMake usage. You can find it here:

http://rix0r.nl/blog/2015/08/13/cmake-guide/

**Comment by rix0rrr** [comment]
It should suffice to add the following command to set every module's includes to take care of the include directories problem:

    target_include_directories(aws-cpp-sdk-something PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
        PRIVATE src)   # Only if you have private headers

**Comment by JonathanHenson** [comment]
Thanks for this. We will very likely add this very soon.

**Comment by JonathanHenson** [comment]
Sorry for the delay. I just added this to our backlog and will be implementing it soon.

**Comment by JonathanHenson** [comment]
I just pushed an update for this. Could you have a look and let me know if that works for you?
Also, I haven't added header file paths yet, would you still prefer the solution you posted to that before?

**Comment by JonathanHenson** [comment]
Thank you for your advice on this. I just pushed an implementation and I am very happy with how this turned out. Build script will look like cmake -Daws-sdk-cpp_DIR=./aws-sdk-cpp/build

I'll be uploading a blog post in the near future to help folks take advantage of this.
