### ISSUE TITLE
Static linking for Windows not working?

### ISSUE THREAD

**Issue by HarmlessDave** [awslabs/aws-sdk-cpp#41]
This is to use the SDK with a native C++ 32-bit app, plain Win32 not MFC.

I tried both of these from a command prompt but Visual Studio shows the project as using a shared DLL:

    E:\cmake-3.1.2-win32-x86\bin\cmake e:\vs12\aws-sdk-cpp-20151111 -G "Visual Studio 12" -STATIC=1

    E:\cmake-3.1.2-win32-x86\bin\cmake e:\vs12\aws-sdk-cpp-20151111 -G "Visual Studio 12" -STATIC_LINKING=1

I tried changing the aws-cpp-sdk-core solution in VS2013 from shared DLL to static (/MT and /MTd) and get build errors:

    2>E:\VS12\aws-sdk-cpp-20151111\aws-cpp-sdk-core\include\aws/core/utils/stream/ResponseStream.h(49): error C2220: warning treated as error - no 'object' file generated
    2>E:\VS12\aws-sdk-cpp-20151111\aws-cpp-sdk-core\include\aws/core/utils/stream/ResponseStream.h(49): warning C4275: non dll-interface class 'std::ios_base' used as base for dll-interface class 'std::basic_ios<char,std::char_traits<char>>'
    2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xiosbase(200) : see declaration of 'std::ios_base'

Do I need to do something else in Cmake to get a static project?

**Comment by bretambrose** [comment]
Try -DSTATIC_LINKING=1

**Comment by HarmlessDave** [comment]
Thanks, that fixed it, I just then needed to change the C++ library link from DLL to static.

Our app is Unicode and this library is only able to build as MBCS.  I'll find out soon whether or not they will work together.
