### ISSUE TITLE
mapping needed between Region and BucketLocationConstraint

### ISSUE THREAD

**Issue by johnny-guo** [awslabs/aws-sdk-cpp#48]
Ideally when doing GetBucketLocationRequest, we can get back a Region instead of another enum BucketLocationConstraint. But looking at these two enum's:

             enum class AWS_CORE_API Region
		{
		    US_EAST_1,
		    US_WEST_1,
		    US_WEST_2,
		    EU_WEST_1,
		    EU_CENTRAL_1,
		    AP_SOUTHEAST_1,
		    AP_SOUTHEAST_2,
		    AP_NORTHEAST_1,
		    SA_EAST_1
		}
		
		
		enum class BucketLocationConstraint
		  {
		    NOT_SET,
		    EU,
		    eu_west_1,
		    us_west_1,
		    us_west_2,
		    ap_southeast_1,
		    ap_southeast_2,
		    ap_northeast_1,
		    sa_east_1,
		    cn_north_1,
		    eu_central_1
		  };

There are some extra "location" in BucketLocationConstraint, i.e. NOT_SET, EU, and cn_north_1 which are not in Region. Can someone explain what are these in terms of Region?

Thanks,
Johnny

**Comment by prestomation** [comment]
Hi Johnny,
EU is the same as eu_west_1. This is an artifact from several years ago when S3 was available in the US and EU before AWS had modern region names. I do not know for sure, but I suspect the only time you'll see EU is if you create a bucket using the BucketLocationConstraint 'EU'. In terms of geography, it is exactly the same as eu_west_1 in Dublin.

NOT_SET is part of the C++ SDK and not modeled by Amazon S3 so you will see this in enums in all clients. It simply represents that the value deserialized the service does not exist in the enum in your client. I think the primary situations this happens is if the service introduces new enum values and you do not update the client and if the member is simply optional and the service does not return it(e.g. it is equivalent to the member not existing in the json or xml payload)

cn_north_1 is AWS China. It is supported by S3, thus you see it in their bucket constraints. We simply have not added it to the SDK's region list. China is a region that is totally separate from the rest of the regions, in that there are different AWS accounts in China.

**Comment by johnny-guo** [comment]
Hi, Preston,

Thank you very much for you elaboration. One more question. In the region, we have US_EAST_1. What is the corresponding BucketLocationConstraint enum? This one seems to be missing.

Thanks,
Johnny

**Comment by prestomation** [comment]
My apologies,

See the S3 documentation here: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html

'When the bucket's region is US Classic, Amazon S3 returns an empty string for the bucket's region:'

**Comment by johnny-guo** [comment]
No apology is needed:-) Thanks, Preston.
