### ISSUE TITLE
Support  for other Environmental variables

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#52]
Hi, I noticed in EnvironmentAWSCredentialsProvider [1], is using the environmental key "AWS_SECRET_KEY_ID".  All of the AWS tools I have used in the path searched for "AWS_SECRET_ACCESS_KEY", supporting this environmental variable may take less people by surprise.

[1] https://github.com/awslabs/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-java/blob/105b4d2f155737404b27e65e58b67dba11c18e19/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java

You are correct. We'll update this and push it out shortly. Thanks for letting us know.

**Comment by JonathanHenson** [comment]
Updated and pushed.
