### ISSUE TITLE
FEATURE REQUEST:  Add support for ObjectMetadata to the TransferClient

### ISSUE THREAD

**Issue by brentnash** [awslabs/aws-sdk-cpp#53]
The TransferClient is really useful for uploading files to S3, but unfortunately it currently only provides one function for doing file uploads:

```
std::shared_ptr<UploadFileRequest> UploadFile(const Aws::String& fileName, const Aws::String& bucketName, const Aws::String& keyName, const Aws::String& contentType, bool createBucket = false, bool doConsistencyChecks = false);
```

If you choose to use the S3Client directly, however, there are more options for specifying different values using things such as the PutObjectRequest.  For instance, the PutObjectRequest allows the user to specify things like the S3 storage class, whether to use Server-Side Encryption or just general object metadata.  It would be great if some of these features were available via the TransferClient as well.

For now, the workaround when these features are required is to just use the S3Client directly and not the TransferClient.

**Comment by JonathanHenson** [comment]
We just merged this update in.
