### ISSUE TITLE
Working code sample for S3?  Document how to construct S3Client with auth and config?

### ISSUE THREAD

**Issue by HarmlessDave** [awslabs/aws-sdk-cpp#54]
The blog post sample does not set a configuration or authentication provider for the S3 client.  The headers do not document how to construct one.  The test harness offers clues but not an example that I can copy.

According to the headers, I can use this:

    S3Client(const Auth::AWSCredentials& credentials, const Client::ClientConfiguration& clientConfiguration = Client::ClientConfiguration());

But that requires me to successfully create those objects.  I poked around the core headers and found this:

    AWSCredentials(const Aws::String& accessKeyId, const Aws::String& secretKey, const Aws::String& sessionToken = ""

But the code below will not compile -- "incomplete type not permitted" 

    const char* secret_id = "foo";
    const char* secret_key = "bar";
    Aws::Auth::AWSCredentials creds(secret_id, secret_key);

I'm guessing I need to do something with < > and AWS::foo but guessing that without documentation or samples is going to be difficult.

**Comment by JonathanHenson** [comment]
I'd recommend against manually constructing credentials. The default constructor will use the default credentials provider chain. This will first check your environment, then your profile config file (~/.aws/credentials), and then check the ec2 metadata service (if you are on ec2 and have an instance profile attached.

Anyways, for explicitly what you are trying to do, you need to #include <aws/core/auth/AWSCredentialsProvider.h>  and then it should work.

We cover this in the video listed in the readme.md

**Comment by HarmlessDave** [comment]
Thanks, and d'oh! I should have thought of the include file but I assumed it was pulled in automatically from the other includes.

> We cover this in the video listed in the readme.md

D'oh! again, I don't normally watch videos to learn an API, I assumed it would be too high-level of an introduction to include details like this.  My bad, I'll Watch The Friendly Manual  :)

**Comment by JonathanHenson** [comment]
No problem. For more context, we try to always forward declare everything to help with build times. Most of the time, you'll have to hunt down a header file if we are only using the type as a reference, return value, or pointer.
