### ISSUE TITLE
Default Timeout is Surprising

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#57]
Not sure if this is a *bug*, but rather it's an opinion.  The default response timeout for `Aws::Client::ClientConfiguration` took me by surprise.  It took me approximately 20 minutes to identify why all of my S3 downloads were failing.

It would be my expectation that the default timeout should be 0 (ie: No response timeout).  Certainly the value of `3000 ms` seems arbitrary.

This error message did help when I looked up libcurl errors (http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
[TRACE] 2015-12-08 01:31:05 CurlHttpClient [139876696389568] 16384 bytes written to response.
[ERROR] 2015-12-08 01:31:05 CurlHttpClient [139876696389568] Curl returned error code 28.
[DEBUG] 2015-12-08 01:31:05 CurlHandleContainer [139876696389568] Releasing curl handle 0x24cee90.
[DEBUG] 2015-12-08 01:31:05 CurlHandleContainer [139876696389568] Notifying waiting threads. 
```

**Comment by JonathanHenson** [comment]
One of the most common and frustrating networking bugs is people NOT setting timeouts on their IO. 3 seconds is fairly standard (especially when hitting tier one services). However, for S3, you may want to increase this limit.
