### ISSUE TITLE
FileStream should flush on network operation complete

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#58]
In gist I have code like this..

```
std::string filePath = "some/local/path";
std::shared_ptr<Aws::Http::HttpRequest>  request;
request->SetResponseStreamFactory(
        [&filePath, &offset]() -> Aws::IOStream* {
            constexpr auto OpenFlag = std::ios_base::out
                                    | std::ios_base::binary;
            Aws::IOStream* ofs =
                Aws::New<Aws::FStream>(ALLOCATION_TAG, filePath, OpenFlag);
            CHECK(ofs->good());
            CHECK(ofs->seekp(offset, ofs->beg));
            return ofs;
        });

std::shared_ptr<Aws::Http::HttpResponse> response(std::move(m_client->MakeRequest(*request)));

std::ifstream ifs(filePath); // ! DATA NOT YET FLUSHED TO FILE HERE
```

However if I artificially scope everything as follows...
```
std::string filePath = "some/local/path";
{ // BEGIN BOGUS SCOPE
std::shared_ptr<Aws::Http::HttpRequest>  request;
request->SetResponseStreamFactory(
        [&filePath, &offset]() -> Aws::IOStream* {
            constexpr auto OpenFlag = std::ios_base::out
                                    | std::ios_base::binary;
            Aws::IOStream* ofs =
                Aws::New<Aws::FStream>(ALLOCATION_TAG, filePath, OpenFlag);
            CHECK(ofs->good());
            CHECK(ofs->seekp(offset, ofs->beg));
            return ofs;
        });

std::shared_ptr<Aws::Http::HttpResponse> response(std::move(m_client->MakeRequest(*request)));
} // END BOGUS SCOPE 

std::ifstream ifs(filePath); // DATA IS NOW FLUSHED
```

This indicates to me a few things:
-  You're not flushing the file stream.
-  You're lazily deleting the Aws::IOstream object

This behavior is surprising and cost me ~45 minute of debug time.

This may /seem obvious/ in this contrived example.  But the entire AWS SDK is designed using *shared pointers practically everywhere*, and as such... it can be come less clear in complicated code what the precise lifetime of objects will be.

**Comment by JonathanHenson** [comment]
Christopher,

The output stream is allocated and given to the response object. In this
case the response object is move only and the stream has the lifetime of
its containing response object. It will be cleaned up when the response is
deleted. Good catch on the missing flush, we'll get an update out to you as
soon as possible.

**Comment by JonathanHenson** [comment]
Oh wait, i just saw the scoping. For that to happen, we'd have to not be
flushing the iostream before deletion. This is most certainly a bug if that
is the case. I'll get a fix out asap.

**Comment by JonathanHenson** [comment]
I just pushed an update to this. Please verify.

**Comment by cjhanks** [comment]
I believe this is resolved.  Tested version `0.9-504-g39e3893`
