### ISSUE TITLE
Undefined reference to AttributeValue::SetS

### ISSUE THREAD

**Issue by ole-johan** [awslabs/aws-sdk-cpp#60]
Hi.

I have successfully compiled the sdk on ubuntu, and have a test-code running where I have connected to a DynamoDB. It goes all the way through a `putItem()` so most of the flow works. However, I am not able to set a value to my attributes. The `putItem()` then, naturally, responds with a `ValidationException`. 

So here is my problem: 
When I try to run 
```
AttributeValue hashKeyAttribute;
hashKeyAttribute.SetS("TestHash");
```
the linker gives me the following error message:
```
/usr/local/include/aws/dynamodb/model/AttributeValue.h:48: error: undefined reference to Aws::DynamoDB::Model::AttributeValue::SetS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

All other aspects of the api seems to work, and as far as I can tell, `AttributeValue` is part of the dynamodb lib, which I evidently must have successfully linked, as I am able to do all the other dynamodb stuff.
Just to be sure, I have linked ALL the libs... :)

Being SO CLOSE to accessing DynamoDB from C++, this is really annoying. Especially because this seems to be a very uncomplicated part of the sdk. :)

What am I missing?

**Comment by JonathanHenson** [comment]
It looks like the library is compiled with custom memory management turned
on, but you are compiling your code without it defined. See the readme for
more info.

**Comment by ole-johan** [comment]
You are absolutely right! :)
Adding a define of `AWS_CUSTOM_MEMORY_MANAGEMENT` did the trick.
Thanks!
