### ISSUE TITLE
Crash in CurlHttpClient

### ISSUE THREAD

**Issue by pokey909** [awslabs/aws-sdk-cpp#63]
The client crashes with a segfault e.g. when the request times out or any other error occurs.

Steps to reproduce:
- Run e.g. s3-integration-test (crashes for me with the default url) with a url that will not respond to the request

Fix submitted as PR #62

**Comment by JonathanHenson** [comment]
I just updated this, check and make sure everything works for you. Reopen if you have any more problems related to this.
