### ISSUE TITLE
getting link error

### ISSUE THREAD

**Issue by msinha31** [awslabs/aws-sdk-cpp#67]
Hi 
I am getting link error 
/home/manisha/RTCode/source_updated/C++/Algorithms/Dig_CP/src/Dig_CP_getScores.cpp: In member function ‘double boss::Dig_CP::getScores::retrieveScore()’:
/home/manisha/RTCode/source_updated/C++/Algorithms/Dig_CP/src/Dig_CP_getScores.cpp:89:25: error: ‘using String = class std::basic_string<char>’ has no member named ‘str’
         hashKey.SetS(ss.str());

code
is 

     Aws::String ss;
        hashKey.SetS(ss.str());

Aws::string is read as  std::basic_string<char> 
-Manisha

**Comment by JonathanHenson** [comment]
If you are using the default build arguments with cmake, you need to be
using Aws::String in your code and passing -DAWS_CUSTOM_MEMORY_MANAGEMENT=1
to your compiler.

Or, you can turn custom memory management off when you build the sdk.

**Comment by msinha31** [comment]
Thanks Jonathan
It works
-Manisha
