### ISSUE TITLE
EC2 DescribeInstances API doesn't work (and likely many others)

### ISSUE THREAD

**Issue by steveniemitz** [awslabs/aws-sdk-cpp#70]
I was attempting to use EC2Client::DescribeInstances, but never got any reservations back.

Digging into the code, it looks like the generated parsers are incorrect.  DescribeInstancesResult looks for a "Reservations" XML node, however the actual XML response is "reservationsSet".  It looks like the generated code isn't looking for the locationName as specified in the API JSON descriptors, and instead only using the member key.

**Comment by steveniemitz** [comment]
It looks like this patch to the code generator template was enough to fix most places:

```
diff --git a/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersDeserializeXml.vm b/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersDeserializeXml.vm
index 6208d31..b01a4c7 100644
--- a/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersDeserializeXml.vm
+++ b/code-generation/generator/src/main/resources/com/amazonaws/util/awsclientgenerator/velocity/cpp/xml/ModelClassMembersDeserializeXml.vm
@@ -29,7 +29,11 @@
 #set($listVarName = $CppViewHelper.computeVariableName($memberName) + "Member")
 #set($listMemberName = "member")
 #end##location specified in model
+#if($member.locationName)##location specified
+    XmlNode ${lowerCaseVarName}Node = resultNode.FirstChild("${member.locationName}");
+#else##no location specified
     XmlNode ${lowerCaseVarName}Node = resultNode.FirstChild("${memberName}");
+#end##
```

I'll submit a PR soon.  Based on the diff, it looks like this mostly impacted EC2 APIs, but there were some changes in S3, SNS, iam, and email as well.

**Comment by steveniemitz** [comment]
Looks like there's a similar problem on the request side as well.  For instance the InstanceIds filter is serialized incorrectly.

**Comment by JonathanHenson** [comment]
thanks for your work on this, after you submit the pull request, I'll rerun the integration tests and make sure we didn't break anything. Ec2 is a special snowflake when it comes to protocol and is unfortunately an edge case we haven't tested too much.

**Comment by steveniemitz** [comment]
Cool, will do.  How do you prefer the commits for this?  Should I do one for the code-gen change and one with the new cpp files, or just all at once?

**Comment by JonathanHenson** [comment]
just the code-gen change. I'll regenerate clients on my end. Once we've verified the fix, we'll regenerate all clients and push them out.

**Comment by steveniemitz** [comment]
Any luck on this / the pull request?

**Comment by JonathanHenson** [comment]
Im testing it now. Should finish today some time.

**Comment by steveniemitz** [comment]
Great!  I'll probably have another PR coming up too to fix the filter serialization.

**Comment by steveniemitz** [comment]
I submitted a preliminary PR for fixing filters, but I'm pretty sure its not 100% correct.  I'd appreciate if you could check it out at some point and comment on it?  Thanks!

https://github.com/awslabs/aws-sdk-cpp/pull/80

**Comment by steveniemitz** [comment]
ping?

**Comment by JonathanHenson** [comment]
so I merged in this pull request, but your other one is almost correct (though breaks SNS). I'm going to regenerate everything and push the new clients up. If you can look at my comments on the other PR, I can get that merged in as soon as it is ready.

**Comment by JonathanHenson** [comment]
just pushed the updates along with fixes for SNS
