### ISSUE TITLE
EC2 SDK is not compiled in linux

### ISSUE THREAD

**Issue by steveniemitz** [awslabs/aws-sdk-cpp#73]
I noticed that the EC2 portion of the SDK isn't included when building on linux.  The comment was that the build hangs in linux.  I removed the conditional that prevents it from being built and eventually (~3.5GB of RAM later) EC2Client.cpp did compile.

This is on Ubuntu 12 / GCC 5.2.

Also, building with clang 3.4 cuts the build time to only a minute or two and ~1.5 GB RAM used to build EC2Client.so

**Comment by JonathanHenson** [comment]
this has been updated and added back.
