### ISSUE TITLE
add -fPIC flag for static build on LINUX

### ISSUE THREAD

**Issue by Eliyahu50** [awslabs/aws-sdk-cpp#77]
Hi,

I'm using the SDK static libraries for working with s3 (aws-sdk-cpp-[core,s3,transfer]). I wanted to create a DSO which statically link with these static libraries (embedding them within the DSO). However when building it, i got a compiler error that the static libraries were built with no PIC support.

I edited the relevant CMakeList.txt files adding the line 
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-fPIC")

I think it worth adding this to the static libraries (at least as optional configuration).

Thanks.

Eliyahu

**Comment by steveniemitz** [comment]
+1 to this, I have a modified CMakeLists as well to add -fPIC to the static libs.

**Comment by JonathanHenson** [comment]
done and merged.

**Comment by Eliyahu50** [comment]
Thanks.
