### ISSUE TITLE
EC2 describevolumes is not working

### ISSUE THREAD

**Issue by johnny-guo** [awslabs/aws-sdk-cpp#84]
Hi,

I'm trying to get volume id with the following code but always get "400" error (bad request):

   ClientConfiguration config;
   config.scheme = Scheme::HTTPS;
   config.connectTimeoutMs = 30000;
   config.requestTimeoutMs = 30000;

   auto client = Aws::MakeShared<EC2Client>("Test", config);

   Filter f1, f2;
   f1.SetName("tag:Name"); f1.AddValues("TestData");
   f2.SetName("attachment.instance-id"); f2.AddValues(getInstanceId());

   DescribeVolumesRequest req; 
   req.AddFilters(f1);
   req.AddFilters(f2);

   DescribeVolumesOutcome out = client->DescribeVolumes(req);
   if (out.IsSuccess())
   {   
      Aws::Vector<Volume> vols = out.GetResult().GetVolumes();
      if (vols[0].GetState() != VolumeState::in_use)
      {   
         LOGGER->Log("Volume is busy");
         return std::string();
      }  

      return vols[0].GetVolumeId().c_str();
   }   
   LOGGER->Log("DescribeVolumeRequest Error: %s", out.GetError().GetMessage().c_str());
   return std::string();

Could someone please shed some light what I have been missing?

Thanks,
Johnny

**Comment by steveniemitz** [comment]
Most of the EC2 API wrappers are broken.  See #70 and https://github.com/tellapart/aws-sdk-cpp/commits/tellapart

I'm working on getting my fixes upstream.  In the meantime you could try out my branch above.

**Comment by JonathanHenson** [comment]
I just pushed updates for this. Check when you get a chance and let us know if you are still having problems.

**Comment by johnny-guo** [comment]
Hi, Steve/Jonathan,

Thanks for the update. Will try it later. 

Thanks again,
Johnny

**Comment by JonathanHenson** [comment]
I just updated this protocol again, can you pull and make sure your code still works?
