### ISSUE TITLE
Constructing EC2Client with ClientConfiguration is dumping core

### ISSUE THREAD

**Issue by johnny-guo** [awslabs/aws-sdk-cpp#86]
After getting the latest bits, constructing EC2Client is breaking(dumping core). Here's the code snippet of how I construct EC2Client:

ClientConfiguration config;
config.scheme = Scheme::HTTPS;
config.connectTimeoutMs = 30000;
config.requestTimeoutMs = 30000;
config.region = Aws::Region::US_WEST_2;
config.verifySSL=true;
EC2Client client(config);

Here's the back trace:
#37 0x00000000008a8d4b in std::__shared_count<2>::__shared_count<Aws::Auth::DefaultAWSCredentialsProviderChain, std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain>>(std::_Sp_make_shared_tag, Aws::Auth::DefaultAWSCredentialsProviderChain *, const std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain> &) (this=0x7fffffffde38, __a=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:502
#38 0x00000000008a8c7f in std::__shared_ptr<Aws::Auth::DefaultAWSCredentialsProviderChain, 2>::__shared_ptr<std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain>>(std::_Sp_make_shared_tag, const std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain> &)
    (this=0x7fffffffde30, __tag=..., __a=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:958
#39 0x00000000008a8c38 in std::shared_ptr<Aws::Auth::DefaultAWSCredentialsProviderChain>::shared_ptr<std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain>>(std::_Sp_make_shared_tag, const std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain> &) (
    this=0x7fffffffde30, __tag=..., __a=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr.h:317
#40 0x00000000008a8b9c in std::allocate_shared<Aws::Auth::DefaultAWSCredentialsProviderChain, std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain>>(std::allocator<Aws::Auth::DefaultAWSCredentialsProviderChain> const&) (__a=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr.h:597
#41 0x0000000000449740 in Aws::MakeShared<Aws::Auth::DefaultAWSCredentialsProviderChain> (allocationTag=0xa0ba23 "EC2Client")
    at /home/fmserver/Project/Shared/AWS/CppSDK/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h:97
#42 0x0000000000423267 in Aws::EC2::EC2Client::EC2Client (this=0x7fffffffe1d8, clientConfiguration=...)
    at /home/fmserver/Project/Shared/AWS/CppSDK/aws-sdk-cpp-master/aws-cpp-sdk-ec2/source/EC2Client.cpp:226
#43 0x0000000000419fcc in getVolumeId () at snapshot.cpp:112
#44 0x000000000041b1f1 in main () at snapshot.cpp:200

The previous build is not working but at least not dumping core... Please help to fix it.

Thanks,
Johnny

**Comment by JonathanHenson** [comment]
can you upload logs and show me your build script?

**Comment by JonathanHenson** [comment]
I'm having a hard time replicating. The Ec2Client is huge, do you think you may be running out of stack space?

**Comment by johnny-guo** [comment]
Hi Jonathan,

Thank you very much for the help. I'm trying to find out the reason too. The problem I have now is if I used the old build(before all the ec2/linux fixes), things are partially working(the part to deal with describing volumes is not working) . I mean it won't dump core. However, if I switch to the new build, it will start dumping core within aws static library. So, I don't think it's running out of stack space. Will go through the code again these days to see where the problem could be. meanwhile, will try to upload a test case later.

Thanks,
Johnny

**Comment by JonathanHenson** [comment]
We turned -fPIC on for static builds. Try turning that back off and see
what happens.

**Comment by JonathanHenson** [comment]
any updates here? This thread has gone stale. Reopen if further correspondence is needed.
