### ISSUE TITLE
Fails to compile using -Wall

### ISSUE THREAD

**Issue by jeremyong** [awslabs/aws-sdk-cpp#87]
There are block style comments littered throughout the codebase (`/* */`) which contain slash-asterisk patterns (e.g. UploadMultipartPartRequest.h:179).

Frankly, block comments I consider an anti-pattern, especially for so many of these comments which are single liners and should be `//` line comments instead. These avoid the tricky parsing problems and are less bug prone.

**Comment by JonathanHenson** [comment]
The /* */ come directly from the documentation on the service models and are used to generate doxygen further down the road. There are also a large number of these that are 50+ lines (and we don't know the difference at generation time). 

Is the warning you are getting that block style comments in general, or that there is a // embedded in it somewhere. If it is the latter, then we can certainly sanitize the contents of the documentation before dropping it into the block.

**Comment by jeremyong** [comment]
There is a /* embedded it in.

**Comment by JonathanHenson** [comment]
I just fixed this and pushed it out. We still use block comments in the javadoc format, but they are better formatted and sanitized now.
