### ISSUE TITLE
Compile errors on Windows 10 / VS2013

### ISSUE THREAD

**Issue by FigBug** [awslabs/aws-sdk-cpp#88]
Compile errors on Windows 10 / VS2013. 

"C:\dev.github\ncontrol\external\aws-sdk-cpp-win\INSTALL.vcxproj" (default target) (1) ->
"C:\dev.github\ncontrol\external\aws-sdk-cpp-win\ALL_BUILD.vcxproj" (default target) (2) ->
"C:\dev.github\ncontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-access-management\aws-cpp-sdk-access-management.vcxproj" (
default target) (3) ->
"C:\dev.github\ncontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-cognito-identity\aws-cpp-sdk-cognito-identity.vcxproj" (de
fault target) (5) ->
"C:\dev.github\ncontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj" (default target) (6) ->
(ClCompile target) ->
  C:\dev.github\ncontrol\external\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/utils/json/JsonSerializer.h(23): fatal
error C1083: Cannot open include file: 'aws/core/external/json-cpp/json.h': No such file or directory [C:\dev.github\nc
ontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
  C:\dev.github\ncontrol\external\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/utils/json/JsonSerializer.h(23): fatal
error C1083: Cannot open include file: 'aws/core/external/json-cpp/json.h': No such file or directory [C:\dev.github\nc
ontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
  C:\dev.github\ncontrol\external\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/utils/json/JsonSerializer.h(23): fatal
error C1083: Cannot open include file: 'aws/core/external/json-cpp/json.h': No such file or directory [C:\dev.github\nc
ontrol\external\aws-sdk-cpp-win\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
  C:\dev.github\ncontrol\external\aws-sdk-cpp\aws-cpp-sdk-core\source\utils\xml\XmlSerializer.cpp(19): fatal error C108
3: Cannot open include file: 'aws/core/external/tinyxml2/tinyxml2.h': No such file or directory [C:\dev.github\ncontrol
\external\aws-sdk-cpp-win\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]

Also, is 32 bit build supported or just 64

**Comment by JonathanHenson** [comment]
try pulling my latest push then adding

 -Daws-sdk-cpp_DIR=<path to the build of the sdk>

 to your cmake arguments for your program. This should resolve everything automatically for you via 

find_package(aws-sdk-cpp)

**Comment by JonathanHenson** [comment]
closing pending more info.
