### ISSUE TITLE
Failed to use DeleteObjectsRequest

### ISSUE THREAD

**Issue by shlomiapel** [awslabs/aws-sdk-cpp#91]
Hi,

i am trying to use DeleteObjectsRequest in order to empty a bucket using the sdk.
All examples i have seen so far have used DeleteObjectRequest to delete every object returned by list.
When generating the request, i receive a 400 bad request response.
The bucket contains more than a 1000 objects.
The list returns a 1000 long list of valid objects from the bucket.

i am using:
ListObjectsRequest listObjectsRequest;
listObjectsRequest.SetBucket(bucketName);

	ListObjectsOutcome listObjectsOutcome = m_pclient->ListObjects(listObjectsRequest);

	if (!listObjectsOutcome.IsSuccess()){
		return false;
	}

	DeleteObjectsRequest delObjReq;
	delObjReq.SetBucket(bucketName);
	Model::Delete deleteObj;
		
	for (const auto& object : listObjectsOutcome.GetResult().GetContents())
	{
		ObjectIdentifier ObjIdent;
		ObjIdent.SetKey(object.GetKey());
		deleteObj.AddObjects(ObjIdent);
	}

	delObjReq.SetDelete(deleteObj);
	DeleteObjectsOutcome delObjOutcome = m_pclient->DeleteObjects(delObjReq);

I keep getting the following error:

<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidRequest</Code>
    <Message>Missing required header for this request: Content-MD5</Message>
    <RequestId>21E6B3D2054E12AB</RequestId>
    <HostId>eyGjYzOlBlRjE/l27FMruM1tw5r10Vw6tbj0teHKxfE9vkfttJsv1sivM113wteE5VNZUmNG7Bg=</HostId>
</Error>

i see that in other requests needing MD5, there is a method for adding it (such as PutObjectRequest).
what am i missing?

i am attaching the sdk log.

[aws_sdk_2016-01-31-11.zip](https://github.com/awslabs/aws-sdk-cpp/files/111215/aws_sdk_2016-01-31-11.zip)

Thanks,
Shlomi

**Comment by JonathanHenson** [comment]
Sorry for the delay. Yes this is definitely a bug. Content-Md5 isn't modeled for the request at all, and according to this: http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html
It should be. I'll reach out to Amazon S3 and see what's going on.

**Comment by JonathanHenson** [comment]
Ok, since this is not an arbitrary payload, such as on PutObject, the SDK needs to automatically do this for you on these requests. I'll make a change to the generated code to handle this.

**Comment by JonathanHenson** [comment]
fixed in latest push.
