### ISSUE TITLE
SQS : Credential should be scoped to a valid region, not 'us-east-1'

### ISSUE THREAD

**Issue by chemidy** [awslabs/aws-sdk-cpp#93]
I'm receiving strange error when trying to send SQS message.

**Unable to parse ExceptionName: SignatureDoesNotMatch Message: Credential should be scoped to a valid region, not 'us-east-1'.**

My Queue location : **https://sqs.us-west-2.amazonaws.com/XXXX/YYYY**

It works like a charm with a us-east location : **https://sqs.us-east-1.amazonaws.com/XXXX/YYYY**

`// create sqs client

    Aws::Client::ClientConfiguration config;
    config.scheme = Aws::Http::Scheme::HTTPS;
    Aws::SQS::SQSClient sqsClient{config};
    try {
        // send message
        Aws::SQS::Model::SendMessageRequest sendMessageRequest;
        sendMessageRequest.SetQueueUrl(myQueueUrl);
        sendMessageRequest.SetMessageBody("{ 'hello':'toto'}");
        Aws::SQS::Model::SendMessageOutcome sendMessageOutcome = sqsClient.SendMessage(sendMessageRequest);

        if(!sendMessageOutcome.IsSuccess() || sendMessageOutcome.GetResult().GetMessageId().length() == 0) {
            std::cout << "AWS Error on sending SQS Message : " << sendMessageOutcome.GetError().GetMessage() << std::endl;
            return 2;
        }
    } catch(...) {
        std::cout << "Exception occurred." << std::endl;
    }`

**Comment by JonathanHenson** [comment]
could you upload your log at trace level?

**Comment by chemidy** [comment]
I try to add log trace, but i got an error during the link

**g++ -std=c++11  -I /usr/local/include/ -L /usr/local/lib/linux/intel64/ -laws-cpp-sdk-sqs -laws-cpp-sdk-core -lstdc++ -laws-cpp-sdk-logs SQSClient.cpp**

/tmp/ccAlw8zu.o: In function `void __gnu_cxx::new_allocator<Aws::Utils::Logging::DefaultLogSystem>::construct<Aws::Utils::Logging::DefaultLogSystem, Aws::Utils::Logging::LogLevel, char const (&) [9]>(Aws::Utils::Logging::DefaultLogSystem*, Aws::Utils::Logging::LogLevel&&, char const (&) [9])':
myclient.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN3Aws5Utils7Logging16DefaultLogSystemEE9constructIS4_JNS3_8LogLevelERA9_KcEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN3Aws5Utils7Logging16DefaultLogSystemEE9constructIS4_JNS3_8LogLevelERA9_KcEEEvPT_DpOT0_]+0x83): undefined reference to `Aws::Utils::Logging::DefaultLogSystem::DefaultLogSystem(Aws::Utils::Logging::LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

**Comment by prestomation** [comment]
Hi chemidy. On your SQS client, you need to set ClientConfiguration.region to your intended region 'US-WEST-2'

Please let us know if you have anymore issues.

**Comment by chemidy** [comment]
Thank you Preston for your help. i really appreciate it.
