### ISSUE TITLE
How to cancel PutObjectAsync/GetObjectAsync requests

### ISSUE THREAD

**Issue by cedral** [awslabs/aws-sdk-cpp#95]
I can't figure out a way to do this. I maid my iostream return an error after an abort but that doesn't work right. Thoughts?

**Comment by JonathanHenson** [comment]
If you use aws-sdk-cpp-transfer-client, it offers this functionality with much more detail. From the low-level client, If you initiate the http client and inject it into the client. Then you can cancel at the http layer.

**Comment by cedral** [comment]
Actually I just figured it out. My error return from the stream + S3Client->DisableRequestProcessing seems to cover it.

**Comment by hanqingwu** [comment]
DisableRequestProcessing is not good ,  it wil stop all client . if  other client is running curcurrent .
