### ISSUE TITLE
Leverage a better async policy or user defined one?

### ISSUE THREAD

**Issue by jeremyong** [awslabs/aws-sdk-cpp#98]
Looking at the implementation (at least for the dynamo db client), asynchronous calls are implemented via `std::async` with the `std::async::launch` policy. In implementation terms, this will simply launch a new thread of execution for each invocation which is *extremely* heavy-handed for a single request. Internally, we have our own thread pool abstractions and will wrap the synchronous calls, but I wanted to call this out as something that isn't idea as a default policy.

**Comment by jeremyong** [comment]
nvm I have found Utils::Threading::Executor

**Comment by JonathanHenson** [comment]
the *Callable functions use a futures interface. For asynchronous behavior you would use the *Async functions. The executor here can be overridden. I will soon push out a pooled executor for people to use instead of the std::thread::detach nonsense.

**Comment by jeremyong** [comment]
That would be nice. As an outsider looking at the code and trying to make it performant, it's hard to reason about what is thread-safe or not

**Comment by JonathanHenson** [comment]
It is thread safe.

**Comment by JonathanHenson** [comment]
The clients and utility classes are thread safe (most don't actually have mutable state.

The model classes need to be protected if you will be writing to them across multiple threads.

**Comment by jeremyong** [comment]
Thanks for the info. I am curious about the thread pool implementation. Many C++ programs may already possess a pool of threads reserved for asynchronous computation, and it would be nice to have an API exposed for AWS clients to post work to or override as necessary.

**Comment by JonathanHenson** [comment]
There is an api for overriding. See Aws::Client::ClientConfiguration
